"""add_content_hash_and_duplicate_of

Revision ID: 09147a946c96
Revises: aa500b7585c9
Create Date: 2026-06-01 14:19:44.145719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09147a946c96'
down_revision: Union[str, Sequence[str], None] = 'aa500b7585c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guideline_versions', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='PDF 본문 SHA-256 (동일 문서 식별용)'))
    op.create_index(op.f('ix_guideline_versions_content_hash'), 'guideline_versions', ['content_hash'], unique=False)
    op.add_column('guidelines', sa.Column('duplicate_of_id', sa.Integer(), nullable=True, comment='동일 콘텐츠(PDF 해시 일치)의 원본 가이드라인 id'))
    op.create_foreign_key(None, 'guidelines', 'guidelines', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guidelines', type_='foreignkey')
    op.drop_column('guidelines', 'duplicate_of_id')
    op.drop_index(op.f('ix_guideline_versions_content_hash'), table_name='guideline_versions')
    op.drop_column('guideline_versions', 'content_hash')
    # ### end Alembic commands ###
