"""initial_tables

Revision ID: 65d7f01470c7
Revises: 
Create Date: 2026-04-15 13:31:47.062761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d7f01470c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='기관 코드 (예: PIPC, KISA)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='기관 정식명칭'),
    sa.Column('short_name', sa.String(length=50), nullable=False, comment='약칭'),
    sa.Column('homepage_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='주요 발행 분야 설명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('crawl_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False, comment="설정 라벨 (예: '가이드라인 자료실')"),
    sa.Column('source_type', sa.Enum('RSS', 'BBS_LIST', 'LAW_API', name='crawlsourcetype'), nullable=False),
    sa.Column('schedule', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='crawlschedule'), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False, comment='대상 URL'),
    sa.Column('list_selector', sa.String(length=500), nullable=True, comment='게시판 목록 CSS 셀렉터'),
    sa.Column('title_selector', sa.String(length=500), nullable=True, comment='제목 CSS 셀렉터'),
    sa.Column('date_selector', sa.String(length=500), nullable=True, comment='날짜 CSS 셀렉터'),
    sa.Column('link_selector', sa.String(length=500), nullable=True, comment='링크 CSS 셀렉터'),
    sa.Column('pagination_param', sa.String(length=50), nullable=True, comment='페이지 파라미터명 (예: pageIndex)'),
    sa.Column('max_pages', sa.Integer(), nullable=False, comment='최대 크롤링 페이지 수'),
    sa.Column('keyword_filter', sa.Text(), nullable=True, comment="쉼표 구분 키워드 필터 (예: '가이드라인,지침,안내서,매뉴얼,기준')"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('basis_type', sa.Enum('GOSI', 'HUNRYEONG', 'YEGYU', 'GOJUNG', name='legalbasistype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='고시/훈령 제목'),
    sa.Column('law_api_id', sa.String(length=50), nullable=True, comment='법제처 행정규칙 ID'),
    sa.Column('promulgation_date', sa.Date(), nullable=True, comment='공포일'),
    sa.Column('enforcement_date', sa.Date(), nullable=True, comment='시행일'),
    sa.Column('parent_law_name', sa.String(length=200), nullable=True, comment='모법명 (예: 개인정보 보호법)'),
    sa.Column('category', sa.Enum('INFO_SECURITY', 'PRIVACY', 'SOFTWARE', 'DATA', 'CLOUD', 'AI', 'E_GOV', 'FINANCE', 'OTHER', name='guidelinecategory'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='crawlrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False, comment='발견된 총 항목 수'),
    sa.Column('items_new', sa.Integer(), nullable=False, comment='신규 항목 수'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['crawl_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_basis_id', sa.Integer(), nullable=False),
    sa.Column('article_ref', sa.String(length=50), nullable=True, comment='근거 조항 (예: 제7조제1항)'),
    sa.Column('description', sa.Text(), nullable=False, comment='위임 내용 요약'),
    sa.Column('expected_guideline_title', sa.String(length=500), nullable=True, comment='예상되는 가이드라인 제목 (매칭용)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_basis_id'], ['legal_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guidelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.Integer(), nullable=True, comment='매칭된 위임 항목 (없으면 자발적 발행)'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('INFO_SECURITY', 'PRIVACY', 'SOFTWARE', 'DATA', 'CLOUD', 'AI', 'E_GOV', 'FINANCE', 'OTHER', name='guidelinecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='가이드라인 개요'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='원문 게시 URL'),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True, comment='PDF 다운로드 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gap_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mandate_id', sa.Integer(), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('MISSING', 'OUTDATED', 'RESOLVED', name='gapstatus'), nullable=False),
    sa.Column('basis_last_amended', sa.Date(), nullable=True, comment='근거 최종 개정일'),
    sa.Column('guideline_last_updated', sa.Date(), nullable=True, comment='가이드라인 최종 갱신일'),
    sa.Column('days_gap', sa.Integer(), nullable=True, comment='개정일~가이드라인 갱신일 차이(일)'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guideline_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=True, comment='버전 표기 (예: v2.0, 2026년판)'),
    sa.Column('published_date', sa.Date(), nullable=False, comment='발행일'),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True, comment='변경사항 요약 (LLM 생성)'),
    sa.Column('significance', sa.Text(), nullable=True, comment='변경 의의 (LLM 생성)'),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guideline_versions')
    op.drop_table('gap_analysis')
    op.drop_table('guidelines')
    op.drop_table('mandates')
    op.drop_table('crawl_runs')
    op.drop_table('legal_bases')
    op.drop_table('crawl_configs')
    op.drop_table('agencies')
    # ### end Alembic commands ###
