"""add_item_type_to_crawl_config

Revision ID: aa500b7585c9
Revises: b343fd2ba2bf
Create Date: 2026-04-24 04:26:23.459826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa500b7585c9'
down_revision: Union[str, Sequence[str], None] = 'b343fd2ba2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'crawl_configs',
        sa.Column(
            'item_type',
            sa.String(length=20),
            nullable=False,
            server_default='guideline',
            comment='소스별 기본 item_type: guideline | announcement',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_configs', 'item_type')
    # ### end Alembic commands ###
