"""add_item_type_to_guideline

Revision ID: b343fd2ba2bf
Revises: 65d7f01470c7
Create Date: 2026-04-24 04:17:36.714492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b343fd2ba2bf'
down_revision: Union[str, Sequence[str], None] = '65d7f01470c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    item_type_enum = sa.Enum('GUIDELINE', 'ANNOUNCEMENT', name='itemtype')
    item_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'guidelines',
        sa.Column(
            'item_type',
            item_type_enum,
            nullable=False,
            server_default='GUIDELINE',  # 기존 row는 모두 guideline으로 기본값
            comment='guideline=실제 가이드라인, announcement=발표·보도자료',
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guidelines', 'item_type')
    # ### end Alembic commands ###
